server:
  port: 8189
  servlet:
    context-path: /
spring:
  datasource:
    username: username
    password: password
  jpa:
    show-sql: true
    open-in-view: false
app:
  old_books: knihy_stare.csv
  new_books: knihy_nove.csv